version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.3-jessie
    steps:
    - checkout
    - run:
        name: 'Middleman build'
        command: make build

workflows:
  version: 2
  workflow:
    jobs:
    - build