version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.3-node
    steps:
    - checkout
    - run:
        name: 'Middleman deploy'
        command: make deploy

workflows:
  version: 2
  workflow:
    jobs:
    - build